stages: [build,deploy,pages]

variables:
  GIT_SUBMODULE_STRATEGY: recursive
  IMAGE_TAG: hugo:$CI_COMMIT_SHA
  USER: gitlab
  CI_URL: http://$CI_ENVIRONMENT_SLUG.blog.ci.yourlabs.io

build:
  stage: build
  image: registry.gitlab.com/pages/hugo:latest
  script:
  - hugo
  artifacts:
    paths:
    - public

docker:
  stage: build
  image: docker:stable
  environment:
    name: hugo/$CI_COMMIT_REF_NAME
    url: http://$CI_ENVIRONMENT_SLUG.blog.ci.yourlabs.io
  script:
  - docker build -t $IMAGE_TAG --build-arg HUGO_URL=$CI_URL .
  except:
  - master

ci:
  stage: deploy
  image: yourlabs/ansible
  before_script:
  - mkdir -p ~/.ssh; echo "$ci_key" > ~/.ssh/id_ed25519; echo "$ci_fingerprint" > ~/.ssh/known_hosts; chmod 700 ~/.ssh; chmod 600 ~/.ssh/*
  environment:
    name: hugo/$CI_COMMIT_REF_NAME
    url: http://hugo:hugo_boss@$CI_ENVIRONMENT_SLUG.blog.ci.yourlabs.io
    on_stop: ci-stop
  script:
  - bigsudo yourlabs.compose project=$CI_COMMIT_REF_NAME compose_hugo_image=$IMAGE_TAG lifetime=604800 hugo@ci.yourlabs.io -v | tee deploy.log
  - grep unreachable=0 deploy.log &> /dev/null
  - grep failed=0 deploy.log &> /dev/null
  except:
  - master

ci-stop:
  stage: deploy
  image: yourlabs/ansible
  variables:
    GIT_STRATEGY: none
  when: manual
  environment:
    action: stop
    name: hugo/$CI_COMMIT_REF_NAME
  script:
  - mkdir -p ~/.ssh; echo "$ci_key" > ~/.ssh/id_ed25519; echo "$ci_fingerprint" > ~/.ssh/known_hosts; chmod 700 ~/.ssh; chmod 600 ~/.ssh/*
  - bigsudo yourlabs.compose down hugo@ci.yourlabs.io project=$CI_COMMIT_REF_NAME -v
  except:
  - master

pages:
  stage: pages
  image: registry.gitlab.com/pages/hugo:latest
  dependencies: [build]
  script:
  - gzip -k -6 $(find public -type f)
  artifacts:
    paths:
    - public
  only:
  - master

prod:
  stage: deploy
  only: [master]
  script:
  - mkdir -p ~/.ssh; echo "$prod_key" > ~/.ssh/id_ed25519; echo "$prod_fingerprint" > ~/.ssh/known_hosts; chmod 700 ~/.ssh; chmod 600 ~/.ssh/*
  - scp -r public/* blog@yourlabs.io:html
  - ssh blog@yourlabs.io sh -c "gzip -k -6 $(find html -type f)"
  artifacts:
    paths:
    - public
