stages: [build, pages]

variables:
  GIT_SUBMODULE_STRATEGY: recursive

build:
  stage: build
  image: node:alpine
  script:
  - apk add g++ hugo
  - yarn install && yarn build
  - hugo
  artifacts:
    paths:
    - static

pages:
  stage: pages
  image: registry.gitlab.com/pages/hugo:latest
  dependencies: [build]
  script:
  - hugo
  artifacts:
    paths:
    - public
  only:
  - master


