variables:
  IMAGE_TAG: $CI_REGISTRY/blog:$CI_COMMIT_SHA
  USER: gitlab

build:
  stage: build
  image: docker:stable
  environment:
    name: hugo/$CI_COMMIT_REF_NAME
    url: http://$CI_ENVIRONMENT_SLUG.blog.ci.yourlabs.io
  script:
  - sed -i "s@https://blog.yourlabs.org@$CI_ENVIRONMENT_URL@" config.toml
  - docker build -t $IMAGE_TAG .
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  - docker push $IMAGE_TAG

test:
  stage: test
  image: yourlabs/ansible
  before_script:
  - mkdir -p ~/.ssh; echo "$ci_key" > ~/.ssh/id_ed25519; echo "$ci_fingerprint" > ~/.ssh/known_hosts; chmod 700 ~/.ssh; chmod 600 ~/.ssh/*
  environment:
    name: hugo/$CI_COMMIT_REF_NAME
    url: http://$CI_ENVIRONMENT_SLUG.blog.ci.yourlabs.io
  script:
  - bigsudo yourlabs.compose project=$CI_COMMIT_REF_NAME compose_hugo_image=$IMAGE_TAG lifetime=604800 hugo@ci.yourlabs.io -v | tee deploy.log
  - grep unreachable=0 deploy.log &> /dev/null
  - grep failed=0 deploy.log &> /dev/null
  except:
    refs:
      - master

test-stop:
  stage: test
  image: yourlabs/ansible
  variables:
    GIT_STRATEGY: none
  when: manual
  environment:
    action: stop
    name: test/$CI_COMMIT_REF_NAME
  script:
  - mkdir -p ~/.ssh; echo "$ci_key" > ~/.ssh/id_ed25519; echo "$ci_fingerprint" > ~/.ssh/known_hosts; chmod 700 ~/.ssh; chmod 600 ~/.ssh/*
  - bigsudo yourlabs.compose down hugo@ci.yourlabs.io project=$CI_COMMIT_REF_NAME -v
  except:
    refs:
      - master

deploy:
  stage: deploy
  image: yourlabs/ansible
  before_script:
  - mkdir -p ~/.ssh; echo "$ci_key" > ~/.ssh/id_ed25519; echo "$ci_fingerprint" > ~/.ssh/known_hosts; chmod 700 ~/.ssh; chmod 600 ~/.ssh/*
  environment:
    name: production
    url: https://yourlabs.org
  script:
  - bigsudo
    yourlabs.compose
    project=$CI_ENVIRONMENT_SLUG
    compose_hugo_image=$IMAGE_TAG
    docker_auth_username=$CI_REGISTRY_USER
    docker_auth_password=$CI_REGISTRY_PASSWORD
    docker_auth_registry=$CI_REGISTRY
    hugo@ci.yourlabs.io
    -v | tee deploy.log
  - grep unreachable=0 deploy.log &> /dev/null
  - grep failed=0 deploy.log &> /dev/null
  only:
    refs:
      - master
