stages: [build, pages]

variables:
  GIT_SUBMODULE_STRATEGY: recursive

build:
  stage: build
  image: alpine:latest
  script:
  - apk add npm g++ hugo
  - touch main.js
  - npm install && npm run build
  - mv dist/* static
  - hugo
  artifacts:
    paths:
    - static

pages:
  stage: pages
  image: registry.gitlab.com/pages/hugo:latest
  dependencies: [build]
  script:
  - hugo
  artifacts:
    paths:
    - public
  only:
  - master


