# All available Hugo versions are listed here: https://gitlab.com/pages/hugo/container_registry
image: registry.gitlab.com/pages/hugo:latest

variables:
  GIT_SUBMODULE_STRATEGY: recursive

test:
  script:
  - hugo
  except:
  - master

pages:
  script:
  - env | grep PAGES
  - sed -i "s@^baseurl.*@baseurl = \"$CI_PAGES_URL\"@" config.toml
  - hugo
  artifacts:
    paths:
    - public
  only:
  - master


