baseurl = "https://blog.yourlabs.org"
contentdir    = "content"
layoutdir     = "layouts"
publishdir    = "public"
title = "Yourlabs"
canonifyurls  = true

DefaultContentLanguage = "en"
metaDataFormat = "yaml"
pygmentsUseClasses = true
pygmentCodeFences = true
enableRobotsTXT = "true"
#disqusShortname = "XXX"
googleAnalytics = "UA-169189134-1"

[Params]
  subtitle = "Hack meets Art"
  logo = "img/logo.png"
  favicon = "img/logo.png"
  dateFormat = "2 January 2006"
  commit = false
  rss = true
  comments = true
  defaultLang = "en"
#  gcse = "012345678901234567890:abcdefghijk" # Get your code from google.com/cse. Make sure to go to "Look and Feel" and change Layout to "Full Width" and Theme to "Classic"
  description ="Yourlabs blog with posts about Continuous integration, Developpement, DevOps, Infra, Security, Automation"

#[[Params.bigimg]]
#  src = "img/triangle.jpg"
#  desc = "Triangle"
#[[Params.bigimg]]
#  src = "img/sphere.jpg"
#  desc = "Sphere"
#[[Params.bigimg]]
#  src = "img/hexagon.jpg"
#  desc = "Hexagon"

[Author]
  name = "Yourlabs"
  email = "contact@yourlabs.org"
  gitlab = "https://yourlabs.io/oss"
  github = "jpic"
  stackoverflow = "users/136008/jpic"

[Languages]
[Languages.en]
languagename = "English"
title = "Yourlabs"
weight = 0

[[Languages.en.menu.main]]
    name = "Home"
    url = "/"
    weight = 1

[[Languages.en.menu.main]]
    name = "Software"
    url = "software/"
    weight = 2

[[Languages.en.menu.main]]
    name = "IT Consulting"
    url = "services/"
    weight = 2

[[Languages.en.menu.main]]
    name = "About"
    url = "about/"
    weight = 10

[[Languages.en.menu.main]]
    name = "Tags"
    url = "tags/"
    weight = 4

[Languages.fr]
languagename = "Français"
title = "Yourlabs"
weight = 1

[[Languages.fr.menu.main]]
    name = "Accueil"
    url = "fr/"
    weight = 1

[[Languages.fr.menu.main]]
    name = "Logiciels"
    url = "fr/software/"
    weight = 2

[[Languages.fr.menu.main]]
    name = "Services"
    url = "fr/services/"
    weight = 2

[[Languages.fr.menu.main]]
    name = "About"
    url = "fr/about/"
    weight = 10

[[Languages.fr.menu.main]]
    name = "Tags"
    url = "fr/tags/"
    weight = 4

