version: '3.5'

services:
  hugo:
    image: nginx
    labels:
    - "traefik.http.routers.blog-${CI_ENVIRONMENT_SLUG}.rule=Host(`fr.${CI_ENVIRONMENT_SLUG}.blog.ci.yourlabs.io`,`${CI_ENVIRONMENT_SLUG}.blog.ci.yourlabs.io`)"
    - "traefik.http.routers.blog-${CI_ENVIRONMENT_SLUG}.entrypoints=web"
    - "traefik.http.middlewares.hugobaseauth.basicauth.usersFile=/htpasswd/hugo"
    - "traefik.http.middlewares.hugobaseauth.basicauth.removeheader=true"
    - "traefik.http.routers.blog-${CI_ENVIRONMENT_SLUG}.middlewares=hugobaseauth"
    - "traefik.enable=true"
    - "traefik.docker.network=web"
    - "traefik.port=80"
    networks:
    - web

networks:
  web:
    external:
      name: web
