name = "Blank"
license = "MIT"
description = "YBS theme"
homepage = "https://yourlabs.io/oss/blog"
tags = ["blog", "plain", "blank", "starter", "development"]
features = ["blog"]
min_version = "0.20"

[author]
  name = "YBS"
  homepage = "https://yourlabs.io"
